### ISSUE TITLE
Ability to export files without header

### ISSUE THREAD

**Issue by ujovlado** [keboola/php-csvmap#4]
Ked parsujem JSON po riadkoch, zaujima ma header len pri prvom riadku. Potom uz chcem len ciste data, ktore budem appendovat na koniec CSVcka.

Bolo by fajn mat option dostat to CSV bez hlavicky.

Trosku som to kukal a asi by sa mi pacilo:
- mat metodu `parseWithoutHeader`
- alebo to posunut o uroven nizsie a mat `getCsvFilesWithoutHeader`

Ak pridem na elegantne riesenie, poslem PR.

**Comment by ujovlado** [comment]
https://github.com/keboola/mongodb-extractor/blob/e52d4b8020157f898fc849abf5d6c510e4a239da/src/Keboola/MongoDbExtractor/Export.php#L109

**Comment by michaljurecko** [comment]
Implemented `bool $writeHeader` https://github.com/keboola/php-csvmap/blob/87ebc40091b3fc14ebda382fbdd6ad7f69639b5f/src/Keboola/CsvMap/Mapper.php#L48
